# Generated by Django 2.2 on 2019-12-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombArea', models.CharField(max_length=150, verbose_name='Nombre Areas')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Area_Competencia',
            fields=[
                ('id_area_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombAreaCompetencia', models.CharField(max_length=150, verbose_name='Nombre Area de Competencia')),
                ('detalle_area_competencia', models.CharField(max_length=500, verbose_name='Descripcion Area de Competencia')),
            ],
            options={
                'db_table': 'area_competencia',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombCompetencia', models.CharField(max_length=75, verbose_name='Nombre Competencia')),
                ('detalle_competencia', models.CharField(max_length=75, verbose_name='Descripcion Competencia')),
                ('id_area_competencia', models.ForeignKey(db_column='id_area_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Area_Competencia')),
            ],
            options={
                'db_table': 'competencia',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id_dependencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombDependencia', models.CharField(max_length=150, verbose_name='Nombre Dependencia')),
                ('id_area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Area')),
            ],
            options={
                'db_table': 'dependencia',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250, verbose_name='Pregunta')),
                ('ayuda', models.CharField(max_length=250, verbose_name='Ayuda para la Pregunta')),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Competencia')),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='TipoCuest',
            fields=[
                ('id_tipoCuest', models.AutoField(primary_key=True, serialize=False)),
                ('nombCuest', models.CharField(max_length=150, verbose_name='Tipo de Cuestionario')),
            ],
            options={
                'db_table': 'tipoCuest',
            },
        ),
        migrations.CreateModel(
            name='TipoDep',
            fields=[
                ('id_tipoDep', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dep', models.CharField(max_length=150, verbose_name='Nombre Tipo de Dependencia')),
            ],
            options={
                'db_table': 'tipoDep',
            },
        ),
        migrations.CreateModel(
            name='TipoUsr',
            fields=[
                ('id_tipoUsr', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=150, verbose_name='Nombre Tipo de Usuario')),
            ],
            options={
                'db_table': 'tipoUsr',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usr', models.AutoField(primary_key=True, serialize=False)),
                ('nombUsuario', models.CharField(max_length=150, verbose_name='Nombre Usuario')),
                ('cedula', models.CharField(max_length=11, verbose_name='Cédula Usuario')),
                ('correo', models.CharField(max_length=75, verbose_name='Correo Usuario')),
                ('clave', models.CharField(max_length=75, verbose_name='Contraseña')),
                ('codigo', models.CharField(max_length=75, verbose_name='Contraseña')),
                ('estado_codigo', models.BooleanField()),
                ('id_dependencia', models.ForeignKey(db_column='id_dependencia', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Dependencia')),
                ('id_tipoUsr', models.ForeignKey(db_column='id_tipoUsr', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.TipoUsr')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='RtaUsr',
            fields=[
                ('id_rtaUser', models.AutoField(primary_key=True, serialize=False)),
                ('rtaUser', models.CharField(max_length=75, verbose_name='Respuesta usuario')),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Pregunta')),
                ('id_usr', models.ForeignKey(db_column='id_usr', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Usuario')),
            ],
            options={
                'db_table': 'rtaUser',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=150, verbose_name='Respuesta pregunta')),
                ('valorRta', models.IntegerField()),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Pregunta')),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id_recomendacion', models.AutoField(primary_key=True, serialize=False)),
                ('recomendacion', models.CharField(max_length=500, verbose_name='Recomendación valor respuesta')),
                ('valor', models.IntegerField()),
                ('id_pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Pregunta')),
            ],
            options={
                'db_table': 'recomendacion',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_tipoCuest',
            field=models.ForeignKey(db_column='id_tipoCuest', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.TipoCuest'),
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('id_competencia', models.ForeignKey(db_column='id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Competencia')),
                ('id_dependencia', models.ForeignKey(db_column='id_dependencia', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Dependencia')),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.AddField(
            model_name='dependencia',
            name='id_tipoDep',
            field=models.ForeignKey(db_column='id_tipoDep', on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.TipoDep'),
        ),
    ]
