# Generated by Django 2.2 on 2020-02-01 16:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0004_auto_20200127_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=250, verbose_name='Respuesta pregunta:'),
        ),
    ]
