# Generated by Django 2.2 on 2020-02-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0005_auto_20200201_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtausr',
            name='rtaUser',
            field=models.IntegerField(verbose_name='Respuesta usuario'),
        ),
    ]
