# Generated by Django 2.2 on 2020-06-29 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0007_auto_20200629_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtausr',
            name='historico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.HistoricoEvaluacion'),
            preserve_default=False,
        ),
    ]
