# Generated by Django 2.2 on 2020-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appWeb", "0008_rtausr_historico"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicoevaluacion",
            options={"verbose_name": "Historial evaluaciones"},
        ),
        migrations.AddField(
            model_name="area_competencia",
            name="image",
            field=models.ImageField(blank=True, upload_to="area-competencia"),
        ),
    ]
