# Generated by Django 2.2 on 2020-09-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appWeb", "0010_auto_20200909_1716"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recomendaciones",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("Basico", "Basico"),
                            ("Intermedio", "Intermedio"),
                            ("Avanzado", "Avanzado"),
                        ],
                        max_length=128,
                    ),
                ),
                ("contenido", models.TextField()),
                (
                    "competencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="appWeb.Competencia",
                        verbose_name="Competencia digital a la que pertenece:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendacion competencia digital",
                "unique_together": {("competencia", "nivel")},
            },
        ),
    ]
