# Generated by Django 2.2 on 2020-09-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appWeb", "0011_recomendaciones"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recomendaciones",
            options={
                "verbose_name": "Recomendacion para subir de nivel",
                "verbose_name_plural": "Recomendacion para subir de nivel",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="ancho_banda",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10Mb", "10Mb"),
                    ("15Mb", "15Mb"),
                    ("mas de 25mb", "mas de 25mb"),
                    ("mas de 50mb", "mas de 50mb"),
                ],
                max_length=32,
                verbose_name="Que ancho de banda de internet tiene?",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("Otro", "Otro"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="numero_computador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("mas de 4", "mas de 4"),
                    ("mas de 6", "mas de 6"),
                ],
                max_length=128,
                verbose_name="Cuantas computadores tiene en su domicilio?",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="numero_moviles",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("mas de 4", "mas de 4"),
                    ("mas de 6", "mas de 6"),
                ],
                max_length=128,
                verbose_name="Cuantos dispositivos moviles tiene en su domicilio?",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tiempo_dispositivo_movil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4h", "4h"),
                    ("6h", "6h"),
                    ("8h", "8h"),
                    ("mas de 10h", "mas de 10h"),
                ],
                max_length=32,
                verbose_name="Cuanto tiempo al dia utiliza un dispositivo movil?",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tipo_computador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Computador de escritorio", "Computador de escritorio"),
                    ("Laptop", "Laptop"),
                ],
                max_length=128,
                verbose_name="Que tipo de computador utiliza?",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tipo_movil",
            field=models.CharField(
                blank=True,
                choices=[("Celular", "Celular"), ("Tablet", "Tablet")],
                max_length=128,
                verbose_name="Que tipo de dispositivo movil utiliza con mas frecuencia?",
            ),
        ),
        migrations.AlterField(
            model_name="recomendaciones",
            name="competencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="subida_nivel",
                to="appWeb.Competencia",
            ),
        ),
    ]
