# Generated by Django 2.2 on 2020-10-18 22:24

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0012_auto_20200910_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_competencia',
            name='info_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=datetime.datetime(2020, 10, 18, 22, 24, 31, 760618, tzinfo=utc), max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencia',
            name='image',
            field=models.ImageField(blank=True, upload_to='img-competencia'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='info_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='ancho_banda',
            field=models.CharField(blank=True, choices=[('10Mb', '10Mb'), ('15Mb', '15Mb'), ('más de 25mb', 'más de 25mb'), ('más de 50mb', 'más de 50mb')], max_length=32, verbose_name='Que ancho de banda de internet tiene?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, choices=[('másculino', 'másculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_computador',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('más de 4', 'más de 4'), ('más de 6', 'más de 6')], max_length=128, verbose_name='Cuantas computadores tiene en su domicilio?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_moviles',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('más de 4', 'más de 4'), ('más de 6', 'más de 6')], max_length=128, verbose_name='Cuantos dispositivos moviles tiene en su domicilio?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tiempo_dispositivo_movil',
            field=models.CharField(blank=True, choices=[('4h', '4h'), ('6h', '6h'), ('8h', '8h'), ('más de 10h', 'más de 10h')], max_length=32, verbose_name='Cuanto tiempo al dia utiliza un dispositivo movil?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_movil',
            field=models.CharField(blank=True, choices=[('Celular', 'Celular'), ('Tablet', 'Tablet')], max_length=128, verbose_name='Que tipo de dispositivo movil utiliza con más frecuencia?'),
        ),
    ]
