# Generated by Django 2.2 on 2021-06-18 04:09

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_matplotlib.fields
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appWeb', '0015_auto_20201018_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_plot', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaCuestionarioGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayuda', models.CharField(max_length=250, verbose_name='Instrucción para la pregunta:')),
                ('pregunta', ckeditor_uploader.fields.RichTextUploadingField(max_length=17500)),
            ],
            options={
                'verbose_name': 'Pregunta Cuestionario General',
                'verbose_name_plural': 'Pregunta Cuestionario General',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ancho_banda',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numero_computador',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numero_moviles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tiempo_dispositivo_movil',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo_computador',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo_movil',
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, choices=[('Másculino', 'Másculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=32),
        ),
        migrations.CreateModel(
            name='RtaUsrGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rta_user', models.CharField(max_length=128, verbose_name='Respuesta usuario')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.HistoricoEvaluacion')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.PreguntaCuestionarioGeneral', verbose_name='Pregunta a la que pertenece:')),
                ('id_usr', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Respuesta realizada por:')),
            ],
            options={
                'verbose_name': 'Respuestas Usuario general',
            },
        ),
        migrations.CreateModel(
            name='RespuestaCuestionarioGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=250, verbose_name='Respuesta pregunta:')),
                ('valorRta', models.CharField(max_length=128, verbose_name='Valor de la respuesta:')),
                ('imagen', image_cropping.fields.ImageCropField(blank=True, max_length=150, upload_to='cursos')),
                ('imagen_crop', image_cropping.fields.ImageRatioField('imagen', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='imagen crop')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.PreguntaCuestionarioGeneral', verbose_name='Pregunta a la que pertenece:')),
            ],
            options={
                'verbose_name': 'Respuesta Cuestionario General',
                'verbose_name_plural': 'Respuestas Cuestionario General',
            },
        ),
    ]
