# Generated by Django 2.2 on 2021-07-16 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0016_auto_20210618_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel Recomendado para dependencia', 'verbose_name_plural': 'Nivel Recomendado para dependencia'},
        ),
        migrations.AddField(
            model_name='competencia',
            name='id_nivel',
            field=models.ForeignKey(db_column='id_nivel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appWeb.Nivel', verbose_name='Nivel Recomendado:'),
        ),
        migrations.AlterUniqueTogether(
            name='nivel',
            unique_together={('id_competencia', 'nivel')},
        ),
        migrations.AlterModelTable(
            name='nivel',
            table=None,
        ),
    ]
