# Generated by Django 2.2 on 2021-07-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0017_auto_20210715_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name': 'Nivel recomendado'},
        ),
        migrations.AlterUniqueTogether(
            name='nivel',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='nivel',
            table='nivel',
        ),
    ]
